---
driver:
  name: vagrant

platforms:
  - name: centos-7
    driver:
      network:
        - [ 'private_network', { ip: '172.28.128.10' } ]
    provisioner:
      name: ansible_playbook
      ansible_connection: winrm
      ansible_inventory: tests/windows/inventory/hosts
      require_windows_support: true
      require_chef_for_busser: false
      ansible_host_key_checking: false
      idempotency_test: true
      playbook: tests/windows/test.yml
    verifier:
      name: shell
      command: echo 'Skipping Verify'

  - name: windows-2k16
    driver:
      box: diodonfrost/windows-2k16
      provision: true
      communicator: winrm
      network:
        - [ 'private_network', { ip: '172.28.128.11' } ]
      customize:
        memory: 2048
      vagrantfiles:
        - tests/vagrant/vagrant_windows_target.rb
    transport:
      name: winrm

verifier:
  name: inspec
  inspec_tests:
    - path: tests/inspec

suites:
  - name: default
