---
dist: bionic
services:
  - docker

language: python
python:
  - "3.7"

env:
#-----------------------------------------------
#
# CentOS
#
#-----------------------------------------------
  - distribution: centos-8
    java_version: latest
  - distribution: centos-8
    java_version: 11
  - distribution: centos-8
    java_version: 8
  - distribution: centos-7
    java_version: latest
  - distribution: centos-7
    java_version: 8
  - distribution: centos-7
    java_version: 7
  - distribution: centos-7
    java_version: 6
  - distribution: centos-6
    java_version: latest
  - distribution: centos-6
    java_version: 8
  - distribution: centos-6
    java_version: 7
  - distribution: centos-6
    java_version: 6

#--------------------------------
#
# Fedora
#
#--------------------------------
  - distribution: fedora-32
    java_version: latest
  - distribution: fedora-32
    java_version: 13
  - distribution: fedora-32
    java_version: 11
  - distribution: fedora-32
    java_version: 8
  - distribution: fedora-31
    java_version: latest
  - distribution: fedora-31
    java_version: 13
  - distribution: fedora-31
    java_version: 11
  - distribution: fedora-31
    java_version: 8
  - distribution: fedora-30
    java_version: latest
  - distribution: fedora-30
    java_version: 12
  - distribution: fedora-30
    java_version: 11
  - distribution: fedora-30
    java_version: 8
  - distribution: fedora-29
    java_version: latest
  - distribution: fedora-29
    java_version: 11
  - distribution: fedora-29
    java_version: 8
  - distribution: fedora-28
    java_version: latest
  - distribution: fedora-28
    java_version: 11
  - distribution: fedora-28
    java_version: 8
  - distribution: fedora-27
    java_version: latest
  - distribution: fedora-27
    java_version: 11
  - distribution: fedora-27
    java_version: 9
  - distribution: fedora-27
    java_version: 8
  - distribution: fedora-26
    java_version: latest
  - distribution: fedora-26
    java_version: 9
  - distribution: fedora-26
    java_version: 8

#--------------------------------
#
# Ubuntu
#
#--------------------------------
  - distribution: ubuntu-20.04
    java_version: latest
  - distribution: ubuntu-20.04
    java_version: 11
  - distribution: ubuntu-20.04
    java_version: 8
  - distribution: ubuntu-18.04
    java_version: latest
  - distribution: ubuntu-18.04
    java_version: 11
  - distribution: ubuntu-18.04
    java_version: 8
  - distribution: ubuntu-16.04
    java_version: latest
  - distribution: ubuntu-16.04
    java_version: 9
  - distribution: ubuntu-16.04
    java_version: 8
  - distribution: ubuntu-14.04
    java_version: latest
  - distribution: ubuntu-14.04
    java_version: 7
  - distribution: ubuntu-14.04
    java_version: 6
  - distribution: ubuntu-12.04
    java_version: latest
  - distribution: ubuntu-12.04
    java_version: 7
  - distribution: ubuntu-12.04
    java_version: 6

#--------------------------------
#
# Debian
#
#--------------------------------
  - distribution: debian-10
    java_version: latest
  - distribution: debian-10
    java_version: 11
  - distribution: debian-9
    java_version: latest
  - distribution: debian-9
    java_version: 8
  - distribution: debian-8
    java_version: latest
  - distribution: debian-8
    java_version: 7

#--------------------------------
#
# Oraclelinux
#
#--------------------------------
  - distribution: oraclelinux-8
    java_version: latest
  - distribution: oraclelinux-8
    java_version: 11
  - distribution: oraclelinux-8
    java_version: 8
  - distribution: oraclelinux-7
    java_version: latest
  - distribution: oraclelinux-7
    java_version: 11
  - distribution: oraclelinux-7
    java_version: 8
  - distribution: oraclelinux-7
    java_version: 7
  - distribution: oraclelinux-7
    java_version: 6
  - distribution: oraclelinux-6
    java_version: latest
  - distribution: oraclelinux-6
    java_version: 8
  - distribution: oraclelinux-6
    java_version: 7
  - distribution: oraclelinux-6
    java_version: 6

#--------------------------------
#
# Amazonlinux
#
#--------------------------------
  - distribution: amazonlinux-2
    java_version: latest
  - distribution: amazonlinux-2
    java_version: 8
  - distribution: amazonlinux-2
    java_version: 7
  - distribution: amazonlinux-1
    java_version: latest
  - distribution: amazonlinux-1
    java_version: 8
  - distribution: amazonlinux-1
    java_version: 7
  - distribution: amazonlinux-1
    java_version: 6

#--------------------------------
#
# Opensuse
#
#--------------------------------
  - distribution: opensuse-leap
    java_version: latest
  - distribution: opensuse-leap
    java_version: 11
  - distribution: opensuse-leap
    java_version: 9
  - distribution: opensuse-leap
    java_version: 8
  - distribution: opensuse-tumbleweed
    java_version: latest
  - distribution: opensuse-tumbleweed
    java_version: 15
  - distribution: opensuse-tumbleweed
    java_version: 14
  - distribution: opensuse-tumbleweed
    java_version: 8
  - distribution: opensuse-15.1
    java_version: latest
  - distribution: opensuse-15.1
    java_version: 11
  - distribution: opensuse-15.1
    java_version: 10
  - distribution: opensuse-15.1
    java_version: 8
  - distribution: opensuse-15
    java_version: latest
  - distribution: opensuse-15
    java_version: 11
  - distribution: opensuse-15
    java_version: 10
  - distribution: opensuse-15
    java_version: 8
  - distribution: opensuse-42.3
    java_version: latest
  - distribution: opensuse-42.3
    java_version: 8
  - distribution: opensuse-42.3
    java_version: 7
  - distribution: opensuse-13.2
    java_version: latest
  - distribution: opensuse-13.2
    java_version: 8
  - distribution: opensuse-13.2
    java_version: 7

#--------------------------------
#
# Archlinux
#
#--------------------------------
  - distribution: archlinux-rolling
    java_version: latest
  - distribution: archlinux-rolling
    java_version: 11
  - distribution: archlinux-rolling
    java_version: 8
  - distribution: archlinux-rolling
    java_version: 7

#--------------------------------
#
# Alpine
#
#--------------------------------
  - distribution: alpine-rolling
    java_version: latest
  - distribution: alpine-rolling
    java_version: 11
  - distribution: alpine-rolling
    java_version: 10
  - distribution: alpine-rolling
    java_version: 8
  - distribution: alpine-rolling
    java_version: 7

before_install:
  - 'docker pull diodonfrost/${distribution}-ansible:latest'

install:
  - 'pip install molecule==3.0.6 docker==4.2.0 ansible==2.9.7'

script:
  - 'distribution=${distribution} java_version=${java_version} molecule test'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
