---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-java"
      include_role:
        name: "ansible-role-java"
      vars:
        java_version: "{{ ansible_env.java_version | default('latest') }}"
