---
# tasks file for install openjdk for Solaris

- name: Install openjre on Solaris
  package:
    name: "{{ openjre_package }}"
    state: present
  when: openjre_install == true

- name: Install openjdk on Solaris
  package:
    name: "{{ openjdk_package }}"
    state: present
  when: openjdk_install == true
