---
# tasks file for install openjdk for Solaris

- name: Install java on Solaris 11
  block:

  - name: Install openjre on Solaris 11
    package:
      name: "{{ openjre_package }}"
      state: present
    when: openjre_install

  - name: Install openjdk on Solaris 11
    package:
      name: "{{ openjdk_package }}"
      state: present
    when: openjdk_install

  when: ansible_distribution_version|int >= 11

- name: Install java on Solaris 10
  block:

  - name: Install openjre on Solaris 10
    pkgutil:
      name: "{{ openjre_package }}"
      state: present
    when: openjre_install

  - name: Install openjdk on Solaris 11
    pkgutil:
      name: "{{ openjdk_package }}"
      state: present
    when: openjdk_install

  - name: Add java binary to path
    file:
      src: "/opt/csw/java/jre/jre{{ java_version }}/bin/java"
      dest: "/bin/java"
      state: link

  when: ansible_distribution_version|int < 11
