---
- name: Verify
  hosts: all
  tasks:
  - name: Solaris | Java should be functionnal
    command: java -version
    ignore_errors: yes
    register: java_result

  - name: Solaris | Verify commands outputs
    assert:
      that:
        - java_result.rc == 0
      success_msg: "All tests passed"
